[package]
name = "rusk-vm"
version = "0.5.0"
authors = [
  "Kristoffer Ström <kristoffer@dusk.network>",
  "zer0 <matteo@dusk.network>"
]
edition = "2018"

[dependencies]
wasmi = "0.6.0"
wasmi-validation = "0.3"
parity-wasm = "0.41"
pwasm-utils = "0.12.0"
failure = "0.1"

dusk-abi = "0.6"
canonical = { version = "0.5" , features = ["host"] }
canonical_host = "0.5"
canonical_derive = "0.5"
dusk-kelvin-map = "0.3"

dusk-bls12_381-sign = { git="https://github.com/dusk-network/bls12_381-sign"}

[dev-dependencies]
dusk-bls12_381 = "0.6"
dusk-bytes = "0.1"

# test contracts
counter = { path = "tests/contracts/counter", features = ["host"] }
fibonacci = { path = "tests/contracts/fibonacci", features = ["host"] }
delegator = { path = "tests/contracts/delegator", features = ["host"] }
stack = { path = "tests/contracts/stack", features = ["host"] }
block_height = { path = "tests/contracts/block_height", features = ["host"] }
self_snapshot = { path = "tests/contracts/self_snapshot", features = ["host"] }
host_fn = { path = "tests/contracts/host_fn", features = ["host"] }
dusk-poseidon = "0.18"

[[bench]]
name = "factorial"
harness = false
