on: [pull_request]

name: Continuous integration

jobs:
  analyze:
    name: Dusk Analyzer
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: --git https://github.com/dusk-network/cargo-dusk-analyzer
      - uses: actions-rs/cargo@v1
        with:
          command: dusk-analyzer

  # We don't run `cargo check` on this repo, since
  # it will only pass if a build has been previously
  # performed. Hence, it is a better idea to only run
  # tests.

  # We don't test on stable for this repo, since
  # no_std and other things in this library
  # depend on the nightly toolchain.

  test_nightly:
    name: Nightly tests
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - run: rustup target add wasm32-unknown-unknown
      - run: make test

  fmt:
    name: Rustfmt
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2020-10-25
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
